server:
  port: 4000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/emeqdb
    username: emeq
    password: password
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  devtools:
    add-properties: true

logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR
